Test

diff --git a/.github/workflows/checkAndSubmitAddonMetadata.yml b/.github/workflows/checkAndSubmitAddonMetadata.yml
--- a/.github/workflows/checkAndSubmitAddonMetadata.yml
+++ b/.github/workflows/checkAndSubmitAddonMetadata.yml
@@ -211,53 +211,62 @@ jobs:
       contents: write
       discussions: write
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v3
-      - name: Check if discussion for this add-on exists
-        id: checkDiscussion
-        run: |
-          addonId=$(
-            echo ${{ needs.getAddonFilename.outputs.addonFileName }} \
-            | sed -r "s|addons/(.*)/.*\.json|\1|g"
-          )
-          jqCode="
-          . | .[\"$addonId\"]
-          | select(
-            .discussionId
-          )
-          "
+    - name: Checkout code
+      uses: actions/checkout@v3
+    - name: Check if discussion for this add-on exists
+      id: checkDiscussion
+      run: |
+        addonId=$(
+          echo ${{ needs.getAddonFilename.outputs.addonFileName }} \
+          | sed -r "s|addons/(.*)/.*\.json|\1|g"
+        )
+        jqCode="
+        . | .[\"$addonId\"]
+        | select(
+          .discussionId
+        )
+        "
   
-          jq -e "$jqCode" submitters.json
-          # -e only sets the exit status of jq to 0 if there is "truthy" output.
-          # If no valid result is produced, i.e. no add-on id is found, jq exits with status 4.
-          # If there is a different error, a different non-zero exit code is used.
-          exit $? # Exit with the same exit code as jq
-      - name: Create discussion for add-on id
-        id: createDiscussion
-        if: failure()
-        uses: abirismyname/create-discussion@v1.1.0
-        env:
-          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}      
-        with:
-          repository-id: 'MDEwOlJlcG9zaXRvcnkyMzI4NDU3MDI='
-          category-id: 'DIC_kwDODeDxhs4CZ6Q6'
-          title: Feelings
-          body: |
-            Let's talk!
-      - name: Add add-on ID and discussion data to json file
-        if: failure()
-        run: |
-          addonId=$(
-            echo ${{ needs.getAddonFilename.outputs.addonFileName }} \
-            | sed -r "s|addons/(.*)/.*\.json|\1|g"
-          )
-          jqCode="
-          .[\"$addonId\"].discussionId = [\"$ {{ createDiscussion.outputs.discussion-id }}\"]
-          | .[\"$addonId\"].discussionUrl = [\"$ {{ createDiscussion.outputs.discussion-url }}\"]
-          "
+        jq -e "$jqCode" discussions.json
+        # -e only sets the exit status of jq to 0 if there is "truthy" output.
+        # If no valid result is produced, i.e. no add-on id is found, jq exits with status 4.
+        # If there is a different error, a different non-zero exit code is used.
+        exit $? # Exit with the same exit code as jq
+    - name: Get add-on version
+      id: getAddonIdAndVersion
+      uses: actions/github-script@v6
+      with:
+        script: |
+          const addonId = ${{ needs.getFilename }}.split('/', 1)
+          core.setOutput('addonId', addonId)
+          const addonVersion = ${{ needs.getFilename  }}.split('/')[2].slice(0, -6)
+          core.setOutput('addonVersion', addonVersion)
+    - name: Create discussion for add-on id
+      id: createDiscussion
+      if: failure()
+      uses: abirismyname/create-discussion@v1.1.0
+      env:
+        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}      
+      with:
+        repository-id: 'MDEwOlJlcG9zaXRvcnkyMzI4NDU3MDI='
+        category-id: 'DIC_kwDODeDxhs4CZ6Q6'
+        title: Reviews for ${{ steps.getAddonIdAndVersion.outputs.addonId }} add-on
+        body: |
+          Version ${{ steps.getAddonIdAndVersion.outputs.version }}
+    - name: Add add-on ID and discussion data to json file
+      if: failure()
+      run: |
+        addonId=$(
+          echo ${{ needs.getAddonFilename.outputs.addonFileName }} \
+          | sed -r "s|addons/(.*)/.*\.json|\1|g"
+        )
+        jqCode="
+        .[\"$addonId\"].discussionId = [\"$ {{ createDiscussion.outputs.discussion-id }}\"]
+        | .[\"$addonId\"].discussionUrl = [\"$ {{ createDiscussion.outputs.discussion-url }}\"]
+        "
   
-          mv discussions.json discussions.old.json
-          jq -e "$jqCode" discussions.old.json > discussions.json
-          jqExitCode=$?
-          rm discuss.old.json
-          exit $jqExitCode
+        mv discussions.json discussions.old.json
+        jq -e "$jqCode" discussions.old.json > discussions.json
+        jqExitCode=$?
+        rm discussions.old.json
+        exit $jqExitCode
